''' 5) ESCREVER UM ALGORITMO PARA LER O CUSTO DE FABRICAÇÃO DE UM CARRO, O CUSTO DE UM CARRO NOVO
AO CONSUMIDOR É A SOMA DO CUSTO DE FÁBRICA COM A PORCENTAGEM DO DISTRIBUIDOR E A PORCENTAGEM 
DOS IMPOSTOS. SUPONDO QUE O PERCENTUAL DO DISTRIBUIDOR SEJA DE 28% E OS IMPOSTOS DE 45% 
EM CIMA DO CUSTO DE FABRICAÇÃO. CALCULAR E ESCREVER O CUSTO FINAL AO CONSUMIDOR. '''

custoFab = float(input("Insira o custo de fabricação do carro: "))

custoCar = custoFab + (0.28 *custoFab) + (0.45 * custoFab)

print(f"O custo final do carro será de R${custoCar}.")